server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
spring: 
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/areuareu?serverTimezone=Asia/Seoul
    username: cos
    password: cos1234
    

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
  devtools:
    livereload:
      enabled: true
  freemarker:
    cache: false 
  
file:
  path: C:/Users/82105/Desktop/gitbut/aruerue-back/src/main/resources/static/images/

  