server:
  port: 8080
  servlet:
    context-path: /
<<<<<<< HEAD
    encoding:
      charset: UTF-8
      enabled: true
      force: true
=======
 
      
servlet:
  multipart:
    enabled: true
    max-file-size: 2MB




>>>>>>> c3ce0af68d3d29589e62f7f56fded8857d096b13
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/areuareu?serverTimezone=Asia/Seoul
<<<<<<< HEAD
    username: areuareu
    password: bitc5600
=======
    username: cos
    password: cos1234
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
  devtools:
    livereload:
      enabled: true
  freemarker:
    cache: false 
      
http:
 encoding:
   charset: UTF-8
   enabled: true
   force: true


file:
  path: C:/Users/82105/Desktop/asdf2/spring-test6/src/main/resources/static/images/
#  C:/src/Springwork/spring-test5/src/main/resources/static/images/
#집에 경로는 달라서 현재 저걸로햇음 
>>>>>>> c3ce0af68d3d29589e62f7f56fded8857d096b13
